baseURL = "http://cdlx.pt"
languageCode = "en-us"
title = "CoderDojo LX"
theme = "github-style"
#googleAnalytics = "UA-123-456-789"
copyright = "© 2020. CoderDojo LX."

[params]
  author = "CoderDojo LX"
  description = "O Sítio Web do CoderDojo LX"
  github = "Sê Fixe!"
  facebook = "coderdojolx/"
  twitter = "coderdojolx"
  email = "lisbon.prt@coderdojo.com"
#  utterances = "jsonapi/matiasilva.github.io"
  avatar = "https://upload.wikimedia.org/wikipedia/commons/9/99/CoderDojo_Logo.png"
  url = "http://coderdojo-lx.pt"
  contributions = "post"
