baseURL: https://coderdojolx.github.io
languageCode: pt-pt
defaultContentLanguage: pt
title: CoderDojo LX
theme: cupper-hugo-theme
googleAnalytics: UA-40757100-3
disqusShortname: yourdiscussshortname
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Um espaço livre e gratuito para jovens dos 7 aos 17 aprenderem programação, electrónica e muito mais!
  homeMetaContent: Um espaço livre e gratuito para jovens dos 7 aos 17 aprenderem programação, electrónica e muito mais!
  footer: Feito com amor pelo [@matias](https://github.com/matiasilva) e cia., usando o [Hugo](https://gohugo.io/) no [Github Pages](https://www.github.com/).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: 2006-01-02
  codePenUser: someUser
  katex: true

menu:
  nav:
    - name: Início
      url: /
      weight: 1
    - name: Inscreve-te!
      url: /signup/
      weight: 2
    - name: A primeira sessão
      url: /first/
      weight: 3
    - name: Quero começar já!
      url: /start/
      weight: 4
    - name: Sessões
      url: /sessions/
      weight: 4
    #- name: Etiquetas
    #  url: /tags/
    #  weight: 10
    # - name: Blog
    #   url: /pot/
    #   weight: 3
    - name: Sobre nós
      url: /about/
      weight: 5
    - name: Contacta-nos
      url: /contact/
      weight: 6
    # - name: RSS
    #   url: /index.xml
    #   weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
