baseURL: https://coderdojolx.github.io
languageCode: en-us
defaultContentLanguage: en
title: CoderDojo LX
theme: cupper-hugo-theme
googleAnalytics: UA-40757100-3
disqusShortname: yourdiscussshortname
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Um espaço livre e gratuito para os jóvens dos 7 aos 17 aprenderem a programação, eletrónica, e muito mais!
  homeMetaContent: Um espaço livre e gratuito para os jóvens dos 7 aos 17 aprenderem a programação, eletrónica, e muito mais!
  footer: Made with love by [@matias](https://github.com/matiasilva) with [Hugo](https://gohugo.io/). Deployed to [Github Pages](https://www.github.com/).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Inscreve-te!
      url: /signup/
      weight: 2
    - name: A primeira sessão
      url: /first/
      weight: 3
    - name: Quero começar já!
      url: /start/
      weight: 4
    # - name: Tags
    #   url: /tags/
    #   weight: 3
    # - name: Blog
    #   url: /pot/
    #   weight: 3
    - name: Sobre nós
      url: /about/
      weight: 5
    # - name: RSS
    #   url: /index.xml
    #   weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
